### ISSUE TITLE
Permalink Incompatibility

### ISSUE THREAD

**Issue by zebfrye** [Ashod/Now-Reading-Redux#1]
Issues:
1. When plugin is enabled with a custom permalink structure already in place library links do not work.
1. If permalinks are resaved in the settings library links start to work but PHP errors are generated.

Warning: preg_match() [function.preg-match]: Compilation failed: nothing to repeat at offset 1 in /**_/**_/***/wp-includes/class-wp.php on line 198 (Repeated several times)

I have disabled all other plugins and tested this plugin by itself.

Plugin was an upgrade from Rob's plugin vs a clean install.

**Comment by Ashod** [comment]
Thanks for reporting this. I'll reproduce it and work on it.

Care to share your library URL?

**Comment by zebfrye** [comment]
Alright. So I figured out the problem. In settings there is a "permalink
base". I figured this was if your blog was at a different location like
blog.domain.com so I didn't set it. Once I set it to "library/" everything
cleared up. You might want to make a note of that in the docs or something
so noobs like me who can't put two and two together don't complain all the
time.

As for my library:

http://www.libertythinker.com/library/ (I'm just working on the templates so
it looks pretty ugly) Hope to add some cool features over the next couple
days.

I also just modded the plugin today to import # of pages in a book from
amazon as well. If you want my modded files let me know.

Also, I don't know if this is still a problem but amazon used to change
their book image links to keep people from hot linking them forever. I just
created a little fix to save the book images to a folder. Don't know if you
want that either. I assume with AWS that they no longer continue that
practice.

**Comment by Ashod** [comment]
Glad it's working for you. Yes, that permalink part is a bit tricky I must say. I'll close this issue then.

Your library looks cool to me. I like the table with rating and "read in" columns. I have some ideas for the library, I'll consider the table format as an option.

My version already pulls the meta information. I just have to add them to the book meta tags. My plan is to include as many meta info as possible.

In my experience with AWS Amazon never did that. Although it would be reasonable to make the plugin pull the images and host them locally. It's the decent thing to do.

Anyway, thanks for your input. If you'd like to share your code, you're more than welcome. However I don't promise to use any of it (usually just writing it out is easier than merging). But rest assured, if I do, you'll get credit.
