### ISSUE TITLE
Post Options

### ISSUE THREAD

**Issue by equip4service** [Ashod/Now-Reading-Redux#2]
Hello. I am in the process of heavily modding this plugin; however, as I am sorting through the code and observing functionality, I have noticed that the “Post Options” – “Add Link to Post” “Transclude Post Content” and “Redirect to Post” seem to have no effect – they all redirect to the blog post. I’m not sure what they are supposed to do, but they all appear to do the same thing or, perhaps, they are deprecated. Please let me know any info that might help. Thanks!

Scott

**Comment by Ashod** [comment]
Scott,

These are placeholders of a feature I'm currently working on. The purpose of the feature is to give the user more control over how links to books behave. Some of us like to publish reviews as normal WP posts and some like to use the book page with the NRR review feature. Both have their own pros and cons. This feature will make it easier for one to have more control over these two options and merge them.

If you'd like to fork the code, please be my guest. You can always merge changes and get the benefit of having your own flavor while keeping up-to-date with other improvements.

Let me know if you need any help.
-Ash
